apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gds-{{kind}}-{{baseName}}-{{environment}}
  name: gds-{{kind}}-{{baseName}}-{{environment}}
  namespace: {{environment}}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gds-{{kind}}-{{baseName}}-{{environment}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gds-{{kind}}-{{baseName}}-{{environment}}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - gds-{{kind}}-{{baseName}}-{{environment}}
            topologyKey: kubernetes.io/hostname
      containers:
      - image: 809853256122.dkr.ecr.{{aws-region}}.amazonaws.com/gds-{{kind}}-{{baseName}}:{{apiImageTag}}
        imagePullPolicy: Always
        name: gds-{{kind}}-{{baseName}}-{{environment}}
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /App/appsettings.json
          name: appsettings-volume
          subPath: appsettings.json
        - mountPath: /App/logs
          name: logs
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        image: 809853256122.dkr.ecr.us-east-1.amazonaws.com/gds-promtail:latest
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 3101
          name: http-metrics
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/promtail
          name: config
          readOnly: true
        - mountPath: /App/logs
          name: logs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: appsettings.json
            path: appsettings.json
          name: gds-{{kind}}-{{baseName}}-{{environment}}-appsettings
        name: appsettings-volume
      - configMap:
          defaultMode: 420
          name: promtail-conf
        name: config
      - emptyDir: {}
        name: logs
