apiVersion: v1
kind: Service
metadata:
  labels:
    app: gds-api-{{baseName}}-{{environment}}
  name: gds-api-{{baseName}}-{{environment}}
  namespace: {{environment}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: gds-api-{{baseName}}-{{environment}}
status:
  loadBalancer: {}
