name: Dispatch to IaC
on: 

  workflow_call:
    inputs:
      destination: 
        required: true
        type: string
      environmment:
        required: true
        type: string
      auto-merge: 
        required: true
        type: string
    secrets:
      app_id:
        required: true
      private_key: 
        required: true      

env: 
  DESTINATION_OWNER: ${{ github.repository_owner }}
  DESTINATION_REPO: ${{ inputs.destination }}

  
jobs:

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a token
        uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
          owner: ${{ github.repository_owner }}

      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat  

      - name: create a repository_dispatch event
        id: post_dispatches
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}   
        with:
          route: POST /repos/${{ env.DESTINATION_OWNER }}/${{ env.DESTINATION_REPO }}/dispatches
          data: '{
            event_type: "${{ github.repository}}", 
            client_payload: {
              sha: "${{ github.sha }}", 
              from: "${{ github.repository}}", 
              branch: "${{ github.ref_name}}",
              auto-merge: "${{ inputs.auto-merge }}" 
            }
          }'
            
    
