name: Deploy API
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      base-name:
        required: true
        type: string
      dockerfile-name:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      repository-sufix:
        required: false
        type: string
      deployment-tag:
        required: false
        type: string
        default: null
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      image:
        description: "Container Image"
        value: ${{ jobs.build-and-publish.outputs.image }}
      repository:
        description: "Container Repository"
        value: ${{ jobs.build-and-publish.outputs.repository }}
      registry: 
        description: "Container Registry"
        value: ${{ jobs.build-and-publish.outputs.registry }}
      

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      regitry: ${{ steps.build-image.outputs.registry }}
      repository: ${{ steps.build-image.outputs.repository }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'GoGipsy/ReusableWorkflows'
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.build-artifact-name }}
    - name: Configure AWS credentials
      id: aws-account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with: 
        mask-password: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.base-name }}${{ inputs.repository-sufix }}
        IMAGE_TAG: ${{ inputs.deployment-tag == null && github.sha || inputs.deployment-tag }}
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      run: |
        docker buildx build \
        --platform="linux/arm64,linux/amd64" \
        --build-arg RELEASE_PATH=${{ github.workspace }}/out \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
        -f ${{ inputs.dockerfile-name }} . \
        --push
        echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "repository=$ECR_REPOSITORY" >> $GITHUB_OUTPUT
        echo "registry=${{ vars.GIPSYY_AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com" >> $GITHUB_OUTPUT
        
