name: Deploy API
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      base-name:
        required: true
        type: string
      dockerfile-name:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      repository-sufix:
        required: false
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      release-image:
        description: "Container Image"
        value: ${{ steps.build-image.outputs.image }}


jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'GoGipsy/ReusableWorkflows'
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.build-artifact-name }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with: 
        mask-password: true
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.base-name }}${{ inputs.repository-sufix }}
        IMAGE_TAG: ${{ github.sha }}
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      run: |
        docker build \
        --build-arg RELEASE_PATH=${{ github.workspace }}/out \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
        -f ${{ inputs.dockerfile-name }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        
