name: Upload to S3

on:
  workflow_call:
    inputs:
      bucket-name:
        required: true
        type: string
      content:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'GoGipsy/ReusableWorkflows'
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.content }}
          path: content
      - name: Upload content to S3
        run: |
           aws s3 sync content s3://${{ inputs.bucket-name }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
