name: package-auth-token
on: 
  workflow_call:
    outputs:
      token: 
        description: "Create token"
        value: ${{ jobs.create.outputs.package-auth-token }}

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      package-auth-token: ${{ steps.auth-token.value }}

    steps:
      #- uses: actions/checkout@v4
      - name: Create Package-Auth-Token
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "value=$TOKEN" >> $GITHUB_OUTPUT
        id: auth-token
