name: Pull Request Checks

on:
  workflow_call:
    inputs:
      coverage-threshold:
        type: number
        description: "The minimum coverage threshold. Below this, the workflow will fail."
        required: false
        default: 90
      go-version:
        type: string
        description: "Go version. Default is 1.21."
        required: false
        default: "1.21"
      go-lint-version:
        type: string
        description: "Go lint version. Default is v1.54."
        required: false
        default: "v1.54"
      runs-on:
        type: string
        description: "Runner to use. Always try to use self-hosted runners."
        required: false
        default: ubuntu-latest

jobs:
  lint:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ github.event.inputs.go-version }}'
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: '${{ github.event.inputs.go-lint-version }}'

  test:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ github.event.inputs.go-version }}'
          cache: false
      - name: Run tests
        run: go test -v ./...
      - name: Get Coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Analyze Coverage
        run: |
          threshold=${{ github.event.inputs.coverage-threshold }}
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          if [ $coverage -lt $threshold ]; then
            echo "Coverage is below threshold ($coverage < $threshold)"
            exit 1
          fi
